# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

project_name: "bindplane-supervisor"

before:
  hooks:
    # Prepare the repository for a release by placing dependencies in the release_deps directory
    - make release-prep VERSION=v{{ .Version }} SUPERVISOR_VERSION={{ envOrDefault "SUPERVISOR_VERSION" "latest" }}

# https://goreleaser.com/customization/build/
builds:
  - id: supervisor
    builder: prebuilt
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    prebuilt:
      path: release_deps/opampsupervisor_{{ .Os }}_{{ .Arch }}{{ .Ext }}
    binary: supervisor

# https://goreleaser.com/customization/archive/
archives:
  - format: tar.gz
    name_template: ""
    files:
      - src: release_deps/LICENSE
        dst: "."
        strip_parent: true
      - src: release_deps/VERSION.txt
        dst: "."
        strip_parent: true
      - src: release_deps/{{ .Os }}/supervisor-config.yaml
        dst: "."
        strip_parent: true
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: supervisor
    ids: 
      - supervisor
    file_name_template: "{{ .PackageName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    package_name: "bindplane-supervisor"
    vendor: Bindplane
    maintainer: Bindplane <support@bindplane.com>
    description: "Bindplane distribution of the OpenTelemetry OpAMP Supervisor"
    homepage: "https://github.com/observIQ/bindplane-supervisor"
    license: "Apache-2.0"
    formats:
      - rpm
      - deb
    bindir: /usr/share/bindplane-supervisor
    scripts:
      preinstall: release_deps/linux/preinstall.sh
      postinstall: release_deps/linux/postinstall.sh
      preremove: release_deps/linux/preremove.sh
      postremove: release_deps/linux/postremove.sh
    contents:
      - dst: /usr/share/bindplane-supervisor
        type: dir
        file_info:
          mode: 0755
      - src: release_deps/{{ .Os }}/supervisor-config.yaml
        dst: /usr/share/bindplane-supervisor/supervisor-config.yaml
        type: config|noreplace
      - src: release_deps/LICENSE
        dst: /usr/share/bindplane-supervisor/LICENSE
      - src: release_deps/VERSION.txt
        dst: /usr/share/bindplane-supervisor/VERSION.txt
      - dst: /usr/share/bindplane-supervisor/supervisor_storage
        type: dir
        file_info:
          mode: 0750
      - dst: /usr/share/bindplane-supervisor/storage
        type: dir
        file_info:
          mode: 0750

# https://goreleaser.com/customization/msi/
msi:
  - id: supervisor-msi
    ids:
      - supervisor
    name: "bindplane-supervisor_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wxs: release_deps/windows/wix.wxs
    extra_files:
      - release_deps/windows/supervisor-config.yaml
      - release_deps/LICENSE
      - release_deps/VERSION.txt